# Generated by Django 5.0.6 on 2024-05-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrepaDuPrepa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=8),
        ),
    ]
